name: Make NDK (musl libc)
run-name: Make NDK-r${{inputs.version}} musl
on:
  workflow_dispatch:
    inputs:
      version:
        description: "NDK Release version:"
        default: '29-beta1'
        required: true
        type: string

jobs:
  make:
    name: Make NDK musl
    runs-on: ubuntu-24.04
    env:
      ZIG_TARGET: ${{matrix.target}}
    strategy:
      fail-fast: false
      matrix:
        target: aarch64-linux-musl
    steps:
      - name: Checkout android-ndk-custom
        uses: actions/checkout@v4
        with:
          path: ${{github.workspace}}

      - name: Set Zig Version
        id: zig_version
        run: |
          case "${{ matrix.target }}" in
            arm-linux-musleabihf|armeb-linux-musleabihf|s390x-linux-musl)
              echo "version=0.15.0-dev.137+db7db4802" >> $GITHUB_OUTPUT
              ;;
            *)
              echo "version=0.15.0-dev.300+9e21ba12d" >> $GITHUB_OUTPUT
              ;;
          esac

      - name: Setup Zig
        uses: mlugg/setup-zig@v2
        with:
          version: "${{ steps.zig_version.outputs.version }}"
          use-cache: false

      - name: Setup Zig Toolchain
        run: git clone https://github.com/HomuHomu833/zig-as-llvm

      - name: Get Official NDK
        run: |
          echo "Downloading NDK r${{inputs.version}}..."
          curl -sSfL -o android-ndk.zip "https://dl.google.com/android/repository/android-ndk-r${{inputs.version}}-linux.zip"
          unzip -qq android-ndk.zip -d ${{ runner.temp }}

      - name: Install Dependencies
        run: |
          sudo add-apt-repository ppa:deadsnakes/ppa -y
          sudo apt update
          sudo apt install -y ninja-build python3.12 \
              build-essential libssl-dev libbz2-dev libdb-dev libgdbm-dev \
              liblzma-dev libsqlite3-dev libreadline-dev libncurses5-dev \
              libncursesw5-dev tk-dev uuid-dev libffi-dev \
              libxml2-dev libxmlsec1-dev zlib1g-dev libcrypt-dev \
              libexpat1-dev libc6-dev-i386 libbluetooth-dev \
              libopus-dev libogg-dev libvorbis-dev libpulse-dev \
              libdb5.3-dev libnsl-dev gawk cmake
          sudo curl -LkSs -o /tmp/qemu-user-binfmt.deb http://ftp.us.debian.org/debian/pool/main/q/qemu/qemu-user-binfmt_10.0.0+ds-2_amd64.deb
          sudo curl -LkSs -o /tmp/qemu-user-static.deb http://ftp.us.debian.org/debian/pool/main/q/qemu/qemu-user-static_10.0.0+ds-2_amd64.deb
          sudo curl -LkSs -o /tmp/qemu-user.deb http://ftp.us.debian.org/debian/pool/main/q/qemu/qemu-user_10.0.0+ds-2_amd64.deb
          sudo apt install -y /tmp/*.deb

      - name: Build Extra Dependencies
        run: |
          TOOLCHAIN=${PWD}/zig-as-llvm
          NDK_DIR="${{ runner.temp }}/android-ndk-r${{inputs.version}}"
          SHADER_TOOLS_BIN="$NDK_DIR/shader-tools/linux-x86_64"
          PREBUILT_BIN="$NDK_DIR/prebuilt/linux-x86_64/bin"
          MAKE_VERSION=$($PREBUILT_BIN/make --version | sed -n '1s/.*GNU Make \([0-9]*\.[0-9]*\).*/\1/p')
          YASM_VERSION=$($PREBUILT_BIN/yasm --version | sed -n '1s/.*yasm \([0-9]*\.[0-9]*\.[0-9]*\).*/\1/p')
          SHADERC_HASH=$(curl -LkSs "https://android.googlesource.com/platform/external/shaderc/shaderc/+/refs/tags/$($SHADER_TOOLS_BIN/glslc --version | sed -n 's/.*\(ndk-[^ ]*\).*/\1/p' | sed 's/+/%2B/g' | head -n 1)" | grep -oP 'href="/platform/external/shaderc/shaderc/\+archive/[a-f0-9]{40}\.tar\.gz"' | sed -E 's/^href="\/platform\/external\/shaderc\/shaderc\/\+archive\///' | sed 's/\.tar\.gz"$//')
          SPIRV_TOOLS_HASH=$(curl -LkSs "https://android.googlesource.com/platform/external/shaderc/spirv-tools/+/refs/tags/$($SHADER_TOOLS_BIN/glslc --version | sed -n 's/.*\(ndk-[^ ]*\).*/\1/p' | sed 's/+/%2B/g' | head -n 1)" | grep -oP 'href="/platform/external/shaderc/spirv-tools/\+archive/[a-f0-9]{40}\.tar\.gz"' | sed -E 's/^href="\/platform\/external\/shaderc\/spirv-tools\/\+archive\///' | sed 's/\.tar\.gz"$//')
          SPIRV_HEADERS_HASH=$(curl -LkSs "https://android.googlesource.com/platform/external/shaderc/spirv-headers/+/refs/tags/$($SHADER_TOOLS_BIN/glslc --version | sed -n 's/.*\(ndk-[^ ]*\).*/\1/p' | sed 's/+/%2B/g' | head -n 1)" | grep -oP 'href="/platform/external/shaderc/spirv-headers/\+archive/[a-f0-9]{40}\.tar\.gz"' | sed -E 's/^href="\/platform\/external\/shaderc\/spirv-headers\/\+archive\///' | sed 's/\.tar\.gz"$//')
          GLSLANG_HASH=$(curl -LkSs "https://android.googlesource.com/platform/external/shaderc/glslang/+/refs/tags/$($SHADER_TOOLS_BIN/glslc --version | sed -n 's/.*\(ndk-[^ ]*\).*/\1/p' | sed 's/+/%2B/g' | head -n 1)" | grep -oP 'href="/platform/external/shaderc/glslang/\+archive/[a-f0-9]{40}\.tar\.gz"' | sed -E 's/^href="\/platform\/external\/shaderc\/glslang\/\+archive\///' | sed 's/\.tar\.gz"$//')

          cd $HOME
          # GNU Make
          curl -LkSs https://ftp.gnu.org/gnu/make/make-$MAKE_VERSION.tar.gz | gzip -d | tar -x
          mv make-$MAKE_VERSION make
          cd make
          cd build-aux
          wget -O config.sub "https://github.com/moonsinnn/android-ndk-custom/raw/refs/heads/$(git -C "${{github.workspace}}" branch --show-current)/config/config.sub"
          wget -O config.guess "https://github.com/moonsinnn/android-ndk-custom/raw/refs/heads/$(git -C "${{github.workspace}}" branch --show-current)/config/config.guess"
          cd ..
          ./configure \
          --prefix="${PWD}/build" \
          --build=${{ matrix.target }} \
          --host=${{ matrix.target }} \
          CC=${TOOLCHAIN}/bin/cc \
          CXX=${TOOLCHAIN}/bin/c++ \
          LD=${TOOLCHAIN}/bin/ld \
          OBJCOPY=${TOOLCHAIN}/bin/objcopy \
          AR=${TOOLCHAIN}/bin/ar \
          STRIP=${TOOLCHAIN}/bin/strip \
          CFLAGS="-fstack-protector-strong -fsanitize=undefined -static" \
          CXXFLAGS="-fstack-protector-strong -fsanitize=undefined -static" \
          LDFLAGS="-static"
          make -j"$(nproc --all)" install

          cd $HOME
          # YASM
          curl -LkSs http://deb.debian.org/debian/pool/main/y/yasm/yasm_$YASM_VERSION.orig.tar.gz | gzip -d | tar -x
          mv yasm-$YASM_VERSION yasm
          cd yasm
          cd config
          wget -O config.sub "https://github.com/moonsinnn/android-ndk-custom/raw/refs/heads/$(git -C "${{github.workspace}}" branch --show-current)/config/config.sub"
          wget -O config.guess "https://github.com/moonsinnn/android-ndk-custom/raw/refs/heads/$(git -C "${{github.workspace}}" branch --show-current)/config/config.guess"
          cd ..
          ./configure \
          --prefix="${PWD}/build" \
          --build=${{ matrix.target }} \
          --host=${{ matrix.target }} \
          --disable-nls \
          CC=${TOOLCHAIN}/bin/cc \
          CXX=${TOOLCHAIN}/bin/c++ \
          LD=${TOOLCHAIN}/bin/ld \
          OBJCOPY=${TOOLCHAIN}/bin/objcopy \
          AR=${TOOLCHAIN}/bin/ar \
          STRIP=${TOOLCHAIN}/bin/strip \
          CFLAGS="-fstack-protector-strong -static -fwrapv -Wno-error=date-time" \
          CXXFLAGS="-fstack-protector-strong -static -fwrapv -Wno-error=date-time" \
          LDFLAGS="-static"
          make -j"$(nproc --all)" install

          # SPIRV-Tools and shaderc
          mkdir -p "$HOME/shaderc"
          cd "$HOME/shaderc"
          curl -LkSs "https://android.googlesource.com/platform/external/shaderc/shaderc/+archive/$SHADERC_HASH.tar.gz" | tar -xz
          cd "$HOME/shaderc/third_party"
          mkdir -p spirv-tools
          cd spirv-tools
          curl -LkSs "https://android.googlesource.com/platform/external/shaderc/spirv-tools/+archive/$SPIRV_TOOLS_HASH.tar.gz" | tar -xz
          cd "$HOME/shaderc/third_party/spirv-tools/external"
          mkdir -p spirv-headers
          cd spirv-headers
          curl -LkSs "https://android.googlesource.com/platform/external/shaderc/spirv-headers/+archive/$SPIRV_HEADERS_HASH.tar.gz" | tar -xz
          cd "$HOME/shaderc/third_party"
          mkdir -p glslang
          cd glslang
          curl -LkSs "https://android.googlesource.com/platform/external/shaderc/glslang/+archive/$GLSLANG_HASH.tar.gz" | tar -xz
          cd "$HOME/shaderc/third_party/spirv-tools"
          git init --quiet
          curl -LkSs "https://github.com/moonsinnn/android-ndk-custom/raw/refs/heads/$(git -C "${{github.workspace}}" branch --show-current)/patches/spirv/full_static.patch" | git apply
          rm -rf .git
          cd "$HOME/shaderc"
          git init --quiet
          curl -LkSs "https://github.com/moonsinnn/android-ndk-custom/raw/refs/heads/$(git -C "${{github.workspace}}" branch --show-current)/patches/shaderc/full_static.patch" | git apply
          rm -rf .git
          cmake -S "$HOME/shaderc" -B "$HOME/shaderc/build" -G Ninja \
            -DCMAKE_INSTALL_PREFIX="$HOME/shaderc/install" \
            -DCMAKE_BUILD_TYPE=MinSizeRel \
            -DCMAKE_C_FLAGS="$([[ "${{ matrix.target }}" == "hexagon-linux-musl" ]] && echo '-Wno-bitfield-width -Wno-error=bitfield-width') -fstack-protector-strong -fsanitize=undefined -static" \
            -DCMAKE_CXX_FLAGS="$([[ "${{ matrix.target }}" == "hexagon-linux-musl" ]] && echo '-Wno-bitfield-width -Wno-error=bitfield-width') -fstack-protector-strong -fsanitize=undefined -static" \
            -DCMAKE_EXE_LINKER_FLAGS="-static" \
            -DCMAKE_CROSSCOMPILING=True \
            -DCMAKE_SYSTEM_NAME=Linux \
            -DCMAKE_C_COMPILER="${TOOLCHAIN}/bin/cc" \
            -DCMAKE_CXX_COMPILER="${TOOLCHAIN}/bin/c++" \
            -DCMAKE_ASM_COMPILER="${TOOLCHAIN}/bin/cc" \
            -DCMAKE_LINKER="${TOOLCHAIN}/bin/ld" \
            -DCMAKE_OBJCOPY="${TOOLCHAIN}/bin/objcopy" \
            -DCMAKE_AR="${TOOLCHAIN}/bin/ar" \
            -DCMAKE_STRIP="${TOOLCHAIN}/bin/strip" \
            -DSHADERC_SKIP_TESTS=ON \
            -DSHADERC_SKIP_EXAMPLES=ON \
            -DCMAKE_POLICY_VERSION_MINIMUM=3.22.1
          cmake --build "$HOME/shaderc/build" --target install

          cd $HOME
          # Python
          curl -LkSs https://www.python.org/ftp/python/3.12.3/Python-3.12.3.tar.xz | xz -d | tar -x
          mv Python-3.12.3 python
          cd python
          sed -i '/case $host_cpu/,/esac/ c MODULE_BUILDTYPE=static' configure
          sed -i '/Linux\*|GNU\*) .*/d' configure
          sed -i '/Linux\*|GNU\*|QNX\*|VxWorks\*|Haiku\*)/,/;;/d' configure
          sed -i '/#include "pycore_pathconfig.h"/a \
          PyObject* _Py_Get_Getpath_CodeObject(void) { Py_RETURN_NONE; }' Modules/getpath_noop.c
          ./configure --prefix="${PWD}/build" \
          --build=${{ matrix.target }} \
          --host=x86_64-linux-gnu \
          --disable-shared \
          --disable-ipv6 \
          --without-pymalloc \
          --enable-optimizations \
          --with-pkg-config=no \
          --with-readline=no \
          --with-ensurepip=no \
          --with-openssl-rpath=no \
          --with-ssl-default-suites=python \
          --with-build-python \
          CC=${TOOLCHAIN}/bin/cc \
          CXX=${TOOLCHAIN}/bin/c++ \
          LD=${TOOLCHAIN}/bin/ld \
          OBJCOPY=${TOOLCHAIN}/bin/objcopy \
          AR=${TOOLCHAIN}/bin/ar \
          STRIP=${TOOLCHAIN}/bin/strip \
          CFLAGS="-fstack-protector-strong -fsanitize=undefined -static -Wno-error=date-time" \
          CXXFLAGS="-fstack-protector-strong -fsanitize=undefined -static -Wno-error=date-time" \
          LDFLAGS="-static" \
          ac_cv_func_dlopen=no ac_cv_file__dev_ptmx=no ac_cv_file__dev_ptc=no
          make -j"$(nproc --all)" build_all || echo "WARNING: issue in building python for ${{ matrix.target }}"
          make install

          # Manually strip binaries
          for file in \
              $HOME/make/build/bin/make \
              $HOME/yasm/build/bin/yasm \
              $HOME/yasm/build/bin/ytasm \
              $HOME/yasm/build/bin/vsyasm \
              $HOME/python/python
          do
              ${TOOLCHAIN}/bin/strip "$file"
          done

      - name: Get LLVM
        run: curl -LkSs https://github.com/${{ github.repository }}/releases/download/llvm-r${{inputs.version}}/bolt+clang+clang-tools-extra+lld-r${{inputs.version}}-${{matrix.target}}.tar.xz | tar -xJf -

      - name: Make NDK musl
        run: |
          NDK="${{ runner.temp }}/android-ndk-r${{inputs.version}}"
          HOST_TOOLCHAIN="${PWD}/bolt+clang+clang-tools-extra+lld-r${{inputs.version}}-${{matrix.target}}"
          NDK_TOOLCHAIN="${NDK}/toolchains/llvm/prebuilt/linux-x86_64"

          find "${NDK_TOOLCHAIN}/bin" -type f | while IFS= read -r file; do
              bname="$(basename "${file}")"
              if [ -f "${HOST_TOOLCHAIN}/bin/${bname}" ] && file "${file}" | grep -q 'ELF'; then
                  echo "Replacing ${bname}"
                  cp "${HOST_TOOLCHAIN}/bin/${bname}" "${file}"
              elif file "${file}" | grep -q 'Bourne-Again shell script'; then
                  echo "Replacing SheBang ${bname}"
                  sed -i 's,#!/usr/bin/env bash,#!/usr/bin/env sh,' "${file}"
              elif ! file "${file}" | grep -Eq 'Python script|Perl script|ASCII text'; then
                  echo "Removing ${bname}"
                  rm ${file}
              fi
          done

          # Fix "Unknown host CPU architecture" in some architectures
          sed -i -E '/case \$HOST_ARCH in/,/esac/ c\
          case $HOST_ARCH in\
            armv5te|armv6|armv6l|armv7|armv7l|armv8l) HOST_ARCH=arm;;\
            armv8b) HOST_ARCH=arm_be;;\
            aarch64) HOST_ARCH=arm64;;\
            aarch64_be) HOST_ARCH=arm64_be;;\
            loongarch64) HOST_ARCH=loong64;;\
            i?86) HOST_ARCH=x86;;\
            amd64) HOST_ARCH=x86_64;;\
            arm64|x86_64|riscv32|riscv64|ppc|ppcle|ppc64|ppc64le|mips|mips64|s390x) HOST_ARCH=$HOST_ARCH;;\
            *) echo "ERROR: Unknown host CPU architecture: $HOST_ARCH"; exit 1;;\
          esac' "${NDK}/build/tools/ndk_bin_common.sh"

          # Remove unused resource
          rm -rf "${NDK_TOOLCHAIN}/python3"
          rm -rf "${NDK_TOOLCHAIN}/musl"
          rm -rf "${NDK}/prebuilt/linux_x86-64/bin/*asm"
          find "${NDK_TOOLCHAIN}/lib" -maxdepth 1 -mindepth 1 -not -name clang -exec rm -rf {} \;
          find "${NDK_TOOLCHAIN}" -maxdepth 5 -path "*/lib/clang/[0-9][0-9]/lib/*" -not -name linux -exec rm -rf {} \;

          # Copy compiled binaries
          cp -R "${HOST_TOOLCHAIN}/lib/clang" "${NDK_TOOLCHAIN}/lib"
          cp -R "${HOST_TOOLCHAIN}/lib/libear" "${NDK_TOOLCHAIN}/lib"
          cp -R "${HOST_TOOLCHAIN}/lib/libscanbuild" "${NDK_TOOLCHAIN}/lib"
          cp $HOME/make/build/bin/make ${NDK}/prebuilt/linux-x86_64/bin
          cp $HOME/yasm/build/bin/yasm ${NDK}/prebuilt/linux-x86_64/bin
          cp $HOME/yasm/build/bin/yasm ${NDK_TOOLCHAIN}/bin
          cp $HOME/yasm/build/bin/ytasm ${NDK}/prebuilt/linux-x86_64/bin
          cp $HOME/yasm/build/bin/vsyasm ${NDK}/prebuilt/linux-x86_64/bin
          cp $HOME/yasm/build/lib/libyasm.a ${NDK}/prebuilt/linux-x86_64/lib
          mkdir -p "${NDK_TOOLCHAIN}/python3/bin"
          mkdir -p "${NDK_TOOLCHAIN}/python3/lib"
          cp $HOME/python/python ${NDK_TOOLCHAIN}/python3/bin/python3
          cp -R $HOME/python/build/lib/python3.12 ${NDK_TOOLCHAIN}/python3/lib
          cp ${{ github.workspace }}/patches/llvm/musl/lldb ${NDK_TOOLCHAIN}/bin/lldb
          chmod 755 ${NDK_TOOLCHAIN}/bin/lldb
          find "${NDK}/shader-tools/linux-x86_64" -type f | while IFS= read -r file; do
             bname="$(basename "${file}")"

             echo "Replacing ${bname}"
             cp "$HOME/shaderc/install/bin/${bname}" "${file}" || true
          done

          if [[ "${{ matrix.target }}" != "x86_64-linux-musl" && "${{ matrix.target }}" != "x86_64-linux-muslx32" ]]; then
            ARCH="${{ matrix.target }}"
            ARCH="${ARCH%%-*}"

            case "$ARCH" in
                aarch64)     ARCH="arm64" ;;
                aarch64_be)  ARCH="arm64_be" ;;
                loongarch64) ARCH="loong64" ;;
                powerpc64le) ARCH="ppc64le" ;;
                powerpc64)   ARCH="ppc64" ;;
                powerpcle)   ARCH="ppcle" ;;
                powerpc)     ARCH="ppc" ;;
            esac

            mv "${NDK}/prebuilt/linux-x86_64" "${NDK}/prebuilt/linux-${ARCH}"
            mv "${NDK}/toolchains/llvm/prebuilt/linux-x86_64" "${NDK}/toolchains/llvm/prebuilt/linux-${ARCH}"
            mv "${NDK}/shader-tools/linux-x86_64" "${NDK}/shader-tools/linux-${ARCH}"

            cd ${NDK}/toolchains/llvm/prebuilt
            ln -s linux-${ARCH} linux-x86_64
            cd ${NDK}/prebuilt
            ln -s linux-${ARCH} linux-x86_64
            cd ${NDK}/shader-tools
            ln -s linux-${ARCH} linux-x86_64

            for file in \
                ${NDK}/ndk-gdb \
                ${NDK}/ndk-lldb \
                ${NDK}/ndk-stack \
                ${NDK}/ndk-which
            do
                sed -i "s|linux-x86_64|linux-${ARCH}|g" $file
            done
          fi

          sed -i -E '/^if\(CMAKE_HOST_SYSTEM_NAME STREQUAL Linux\)$/,/^endif\(\)$/c\
          if(CMAKE_HOST_SYSTEM_NAME STREQUAL Linux OR CMAKE_HOST_SYSTEM_NAME STREQUAL Android)\
              execute_process(\
                  COMMAND uname -m\
                  OUTPUT_VARIABLE HOST_ARCH\
                  OUTPUT_STRIP_TRAILING_WHITESPACE\
              )\
          \
              # Normalize uname -m to Android NDK host tags\
              if(HOST_ARCH STREQUAL "aarch64")\
                  set(ARCH "arm64")\
              elseif(HOST_ARCH MATCHES "^armv[0-9]+l$")\
                  set(ARCH "arm")\
              elseif(HOST_ARCH STREQUAL "arm64" OR HOST_ARCH STREQUAL "arm64e")\
                  set(ARCH "arm64")\
              elseif(HOST_ARCH STREQUAL "aarch64_be")\
                  set(ARCH "arm64_be")\
              elseif(HOST_ARCH STREQUAL "loongarch64")\
                  set(ARCH "loong64")\
              elseif(HOST_ARCH STREQUAL "riscv64")\
                  set(ARCH "riscv64")\
              elseif(HOST_ARCH STREQUAL "powerpc64le")\
                  set(ARCH "ppc64le")\
              elseif(HOST_ARCH STREQUAL "powerpc64")\
                  set(ARCH "ppc64")\
              elseif(HOST_ARCH STREQUAL "powerpcle")\
                  set(ARCH "ppcle")\
              elseif(HOST_ARCH STREQUAL "powerpc")\
                  set(ARCH "ppc")\
              elseif(HOST_ARCH STREQUAL "amd64")\
                  set(ARCH "x86_64")\
              elseif(HOST_ARCH MATCHES "^i[3-6]86$")\
                  set(ARCH "x86")\
              else()\
                  set(ARCH "${HOST_ARCH}")\
              endif()\
          \
              set(ANDROID_HOST_TAG "linux-${ARCH}")\
          \
          elseif(CMAKE_HOST_SYSTEM_NAME STREQUAL Darwin)\
              set(ANDROID_HOST_TAG "darwin-x86_64")\
          elseif(CMAKE_HOST_SYSTEM_NAME STREQUAL Windows)\
              set(ANDROID_HOST_TAG "windows-x86_64")\
          endif()' "${NDK}/build/cmake/android.toolchain.cmake" "${NDK}/build/cmake/android-legacy.toolchain.cmake"

      - name: Archive
        run: |
          cd ${{ runner.temp }}
          tar -cf - android-ndk-r${{inputs.version}} | xz -T0 -9e --lzma2=dict=256MiB > android-ndk-r${{inputs.version}}-${{matrix.target}}.tar.xz
          mv android-ndk-r${{inputs.version}}-${{matrix.target}}.tar.xz ${{ github.workspace }}

      - name: Release
        uses: ncipollo/release-action@v1.16.0
        with:
          tag: "r${{inputs.version}}"
          artifacts: android-ndk-r${{inputs.version}}-${{matrix.target}}.tar.xz
          allowUpdates: true
          replacesArtifacts: true
          body: ''
